### ISSUE TITLE
Small gas optimisation (massNotify)

### ISSUE THREAD

**Issue by ryu9827** [BlockchainLabsNZ/etheal-contracts#15]
Assigning _owner.length to a local variable costs more than directly using the array length.
```
function massNotify(address[] _owners) public onlyOwner {
        uint256 count = _owners.length; //should get rid of this line
        for (uint256 i = 0; i < count; i++) {  //should use array length
            Transfer(address(0), _owners[i], VIRTUAL_COUNT);
        }
    }
```

Test result: It costs around 10 gas more on calling this function each time.
Test tx on Kovan testnet:
with local variable:  [0xde3bdd](https://kovan.etherscan.io/tx/0xde3bdd36a133b8e26961cf52d76db15e2735db28536130102d427ed523d2c04c)
Without local variable:  [0x015c8e](https://kovan.etherscan.io/tx/0x015c8e59e486333afbb6e16792cf0670fc0a82920de57c6539f95f2000ea3cc5)

**Comment by thesved** [comment]
fixed: https://github.com/thesved/etheal-sale/commit/c41e06ed5daa912acc3f04c29638eedb3cb46e6c
