### ISSUE TITLE
Variable type declarations should be consistent

### ISSUE THREAD

**Issue by ryu9827** [BlockchainLabsNZ/etheal-contracts#16]
It is recommended to explicitly define your variable types, this confirms your intent and safeguards against a future when the default type changes. It is better to keep them consistent in the same contract.

```
    /// @notice needed for hodler handling
    function addHodlerStake(address _beneficiary, uint _stake) public;
    function setHodlerStake(address _beneficiary, uint256 _stake) public;
    function setHodlerTime(uint256 _time) public;
```

**Comment by thesved** [comment]
Please @ryu9827 can you specify where did you find the addHodlerStake with uint argument?

**Comment by ryu9827** [comment]
Hi @thesved , it is in TokenController.sol, line 11. Sorry for not being specific.

**Comment by thesved** [comment]
@ryu9827 thank you, please find the fixed commit here: https://github.com/thesved/etheal-sale/commit/32370ca3b789cf57af5be14f57174265d9ffb216
