### ISSUE TITLE
Expected '{' after for statement

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/etheal-contracts#3]
https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealNormalSale.sol#L344

See here for fix:

![default](https://user-images.githubusercontent.com/17868193/32705056-86539ace-c874-11e7-965a-98ff6257cd6a.png)

**Comment by thesved** [comment]
https://github.com/thesved/etheal-sale/commit/908389dd18cf892aaff28c19536459dcc434571b
