### ISSUE TITLE
Keep formatting of if statements consistent

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/etheal-contracts#5]
We would recommend avoiding single line `if` statements without using braces, this pattern is prone for introducing bugs. 

Examples:
`EthealPreSale.sol`
[Line 420](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L420)
[Line 142](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L142)
[Line 177](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L177)
[Line 420](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L420)
[Line 431](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L431)
[Line 438](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L438)

Examples where braces are used for a single line if:
[Line 156](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L156)
[Line 169](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L169)
[Line 214](https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealPreSale.sol#L214)

**Comment by matt-lough** [comment]
Code style is subjective, but here is some discussion on the subject:

https://softwareengineering.stackexchange.com/questions/16528/single-statement-if-block-braces-or-no

https://stackoverflow.com/questions/2125066/is-it-bad-practice-to-use-an-if-statement-without-brackets

**Comment by thesved** [comment]
https://github.com/thesved/etheal-sale/commit/22f606f67e93cf972431a1add9c21b14738aab77
