### ISSUE TITLE
The constant keyword is being used in functions, this will be deprecated at the next breaking release

### ISSUE THREAD

**Issue by matt-lough** [BlockchainLabsNZ/etheal-contracts#7]
`constant` should not be used for functions, it is going to be invalid at the next breaking release of solidity. (https://github.com/ethereum/solidity/issues/992)

Some of your functions have already been changed to `view` or `pure` but this is no consistent.

More info: https://ethereum.stackexchange.com/questions/25200/solidity-what-is-the-difference-between-view-and-constant

**Comment by thesved** [comment]
https://github.com/thesved/etheal-sale/commit/641e021abecc50da0413683ed90e53d0de36ad41

I left the wallet untouched, since it is a well-tested consensys multisig wallet, which will hold all the contributions, and I don't feel comfortable to change it.

**Comment by OperationNine** [comment]
Yes this is understandable
